services:

  tg_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg_bot
    working_dir: /app
    volumes:
      - .:/app
    command: python main.py
    env_file:
      - .env
#    depends_on:
#      - postgres
#    networks:
#      - backend
#
#
#  postgres:
#    container_name: postgres
#    image: postgres:13.3
#    environment:
#      POSTGRES_DB: ${DB__NAME}
#      POSTGRES_USER: ${DB__USER}
#      POSTGRES_PASSWORD: ${DB__PASS}
#    ports:
#      - "${DB__PORT1}:${DB__PORT2}"
#    volumes:
#      - db_data:/var/lib/postgresql/data:cached
#    networks:
#      - backend
#
#volumes:
#  db_data:
#
#networks:
#  backend:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 172.28.0.0/16